query bannerCollection($paginationArgs: PaginationArgs) {
  bannerCollection(paginationArgs: $paginationArgs) {
    items {
      active
      id
      image
      name
      priority_number
    }
    meta {
      currentPage
      hasNextPage
      hasPreviousPage
      limit
      totalItem
      totalPage
    }
  }
}
