query brandCollection($pagination: PaginationArgs) {
  brandCollection(pagination: $pagination) {
    items {
      id
      name
      models {
        id
        name
      }
    }
    meta {
      currentPage
      hasNextPage
      hasPreviousPage
      limit
      totalItem
      totalPage
    }
  }
}
